version: "3.8"
services:
  backend:
    image: ghcr.io/sports-day/sportsdayapi:main
    restart: always
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - backend.env
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mariadb:lts-jammy
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sports_day
      - TZ='Asia/Tokyo'
    ports:
      - 33060:3306
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=database
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3030:80"
