services:
  backend:
    image: ghcr.io/sports-day/sportsdayapi:main
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - AZURE_AD_TENANT_ID=72fe835d-5e95-4512-8ae0-a7b38af25fc8
      - DATABASE_DB=sports_day
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=3306
      - DATABASE_USER=root
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mariadb:lts-jammy
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sports_day
      - TZ='Asia/Tokyo'
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=database
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3030:80"
